[versions]
composeDesktop = "1.6.20-dev1646"
ideaGradlePlugin = "2.0.0-beta3"
kotlin = "1.9.24"
kotlinxSerialization = "1.5.1"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Plugin libraries for build-logic's convention plugins to use to resolve the types/tasks coming from these plugins
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
composeDesktop = { id = "org.jetbrains.compose", version.ref = "composeDesktop" }
ideaGradlePlugin = { id = "org.jetbrains.intellij.platform", version.ref = "ideaGradlePlugin" }
